# Generated by Django 6.0 on 2025-12-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.subject'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='content_type',
            field=models.CharField(choices=[('youtube', 'YouTube Video'), ('uploaded', 'Uploaded Video'), ('external', 'External Link')], default='youtube', max_length=20),
        ),
    ]
