# Generated by Django 6.0 on 2025-12-28 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_topic_subject_alter_videocontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.topic'),
        ),
    ]
