# Generated by Django 6.0 on 2025-12-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_videocontent_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={},
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='views',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='youtube_id',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo या किसी अन्य video platform का link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='content_type',
            field=models.CharField(choices=[('youtube', 'YouTube Video'), ('uploaded', 'Uploaded Video'), ('vimeo', 'Vimeo Video'), ('external', 'External Link')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic'),
        ),
    ]
