# Generated by Django 6.0 on 2025-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_videocontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video Content', 'verbose_name_plural': 'Video Contents'},
        ),
        migrations.AddField(
            model_name='videocontent',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True, verbose_name='Duration (seconds)'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Thumbnail Image'),
        ),
    ]
