# Generated by Django 6.0 on 2025-12-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_videocontent_options_videocontent_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended size: 400x225px', null=True, upload_to='video_thumbnails/%Y/%m/%d/', verbose_name='Thumbnail'),
        ),
    ]
