# Generated by Django 6.0 on 2025-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_videocontent_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='YouTube thumbnail URL (auto-fetched)', max_length=500, null=True, verbose_name='Thumbnail URL'),
        ),
    ]
