# Generated by Django 6.0 on 2025-12-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_videocontent_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload thumbnail image (400x225px recommended)', null=True, upload_to='video_thumbnails/%Y/%m/%d/', verbose_name='Thumbnail Image'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='content_type',
            field=models.CharField(choices=[('youtube', 'YouTube Video'), ('uploaded', 'Uploaded Video'), ('vimeo', 'Vimeo Video')], default='youtube', max_length=20, verbose_name='Video Source'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Video Title'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic', verbose_name='Related Topic'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter complete video URL (YouTube, Vimeo, etc.)', max_length=500, null=True, verbose_name='Video URL'),
        ),
    ]
