# Generated by Django 6.0 on 2025-12-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_videocontent_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='duration',
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='content_type',
            field=models.CharField(choices=[('youtube', 'YouTube Video'), ('uploaded', 'Uploaded Video'), ('vimeo', 'Vimeo Video')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.topic'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or other video URL', max_length=500, null=True),
        ),
    ]
