# Generated by Django 6.0 on 2025-12-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_videocontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedcontent',
            name='additional_resources',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='detailedcontent',
            name='important_points',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='detailedcontent',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='detailedcontent',
            name='practice_questions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
