# Generated by Django 6.0 on 2025-12-29 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_category_options_alter_detailedcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.category'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='duration',
            field=models.CharField(blank=True, default='10:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='detailedcontent',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
